# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ub2 < Formula
  desc ""
  homepage ""
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Abhishekkarunakaran/ub2/releases/download/v1.1.1/ub2_Darwin_x86_64.tar.gz"
      sha256 "160038d489889aeba8a82b2404f8d01b074787a3c4160ac60044952270dfd3df"

      def install
        bin.install "ub2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Abhishekkarunakaran/ub2/releases/download/v1.1.1/ub2_Darwin_arm64.tar.gz"
      sha256 "33f83c1898bd26337e0abf0556748bf7906b9e3c00b1d62a330b1890d435408e"

      def install
        bin.install "ub2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Abhishekkarunakaran/ub2/releases/download/v1.1.1/ub2_Linux_x86_64.tar.gz"
        sha256 "bf847fb7be48bfb30cca33fb0aa924b5f8e200be1854d863e9ae0061833cddc3"

        def install
          bin.install "ub2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Abhishekkarunakaran/ub2/releases/download/v1.1.1/ub2_Linux_arm64.tar.gz"
        sha256 "90efd6fb018da1878c51d5a5087bc8f3a3eac44fc1651ba066b1e1279cceb57f"

        def install
          bin.install "ub2"
        end
      end
    end
  end
end
